backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "المنتجات والعروض"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج أو الغرفة", name: "title", widget: "string" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "صورة المنتج الرئيسية", name: "image", widget: "image" }
      - { label: "السعر (اختياري)", name: "price", widget: "string", required: false }
      - { label: "تفاصيل ووصف المنتج", name: "body", widget: "markdown" }
